# Generated by Django 2.2.1 on 2019-05-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeConge', models.CharField(max_length=100, null=True)),
                ('quota', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='demandeConge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbjourdemnade', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDepart', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=100, null=True)),
                ('cin', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('dateNaiss', models.DateField(null=True)),
                ('dateRecrut', models.DateField(null=True)),
                ('Dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFonction', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomService', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100, null=True)),
                ('echelle', models.CharField(max_length=100, null=True)),
                ('salaireBase', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='validatConge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('etat', models.CharField(max_length=100, null=True)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demandeConge')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='validatAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.validatAbsence')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='Fonction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Fonction'),
        ),
        migrations.AddField(
            model_name='employe',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Service'),
        ),
        migrations.AddField(
            model_name='employe',
            name='Statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Statut'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employe'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='typeconge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Conge'),
        ),
        migrations.CreateModel(
            name='demandeAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbheure', models.IntegerField(null=True)),
                ('period', models.CharField(max_length=100, null=True)),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='authentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('typecompte', models.CharField(max_length=100, null=True)),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employe')),
            ],
        ),
    ]
