# Generated by Django 2.2.1 on 2019-05-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='datedebut',
            field=models.DateField(null=True),
        ),
    ]
