# Generated by Django 2.2.1 on 2019-06-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='salaireBase',
            field=models.IntegerField(null=True),
        ),
    ]
