# Generated by Django 2.2.1 on 2019-06-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_demandeconge_datedebut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeabsence',
            name='heurabsence',
            field=models.TimeField(null=True),
        ),
    ]
