# Generated by Django 2.2.1 on 2019-06-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_demandeabsence_heurabsence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeabsence',
            name='nbheure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
